spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: hotdeal
#      username: taptorestart
#      password: thisispass
#      authentication-database: admin

server:
  port: 8080
  servlet:
    context-path: "/api"

#spring:
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      database: hotdeal